frontend_get_map:
    path:     /get-clubes
    defaults: { _controller: "FrontendBundle:Map:getClubes" }
    methods:  GET

frontend_get_club:
    path:     /get-club
    defaults: { _controller: "FrontendBundle:Map:getClub" }
    methods:  [POST]


