frontend_get_match_random:
    path:     /get-match-random
    defaults: { _controller: "FrontendBundle:Match:getMatchRandom" }
    methods:  GET

frontend_get_matchs:
    path:     /get-matchs
    defaults: { _controller: "FrontendBundle:Match:getMatchs" }
    methods:  [POST]
    
frontend_get_all_matchs:
    path:     /get-all-matchs
    defaults: { _controller: "FrontendBundle:Match:getAllMatchs" }
    methods:  GET

frontend_new_match:
    path:     /new-match
    defaults: { _controller: "FrontendBundle:Match:newMatch" }
    methods:  [POST]

frontend_check_match:
    path:     /check-match
    defaults: { _controller: "FrontendBundle:Match:checkMatch" }
    methods:  [POST]

frontend_upload_match:
    path:     /upload-score
    defaults: { _controller: "FrontendBundle:Match:uploadScore" }
    methods:  [POST]

