frontend_get_tournament_random:
    path:     /get-tournament-random
    defaults: { _controller: "FrontendBundle:Tournament:getTournamentRandom" }
    methods:  GET

frontend_get_tournament:
    path:     /get-tournament
    defaults: { _controller: "FrontendBundle:Tournament:getTournament" }
    methods:  POST
    
frontend_get_tournaments:
    path:     /get-tournaments
    defaults: { _controller: "FrontendBundle:Tournament:getTournaments" }
    methods:  GET

frontend_new_tournament:
    path:     /new-tournament
    defaults: { _controller: "FrontendBundle:Tournament:newTournament" }
    methods:  POST
    
frontend_get_my_tournaments:
    path:     /get-my-tournaments
    defaults: { _controller: "FrontendBundle:Tournament:getMyTournaments" }
    methods:  POST
    
frontend_inscription:
    path:     /inscription
    defaults: { _controller: "FrontendBundle:Tournament:inscription" }
    methods:  POST
    
frontend_upload_tournament:
    path:     /upload-score
    defaults: { _controller: "FrontendBundle:Tournament:uploadScore" }
    methods:  [POST]