frontend_complete_profile:
    path:     /complete-profile
    defaults: { _controller: "FrontendBundle:User:completeProfile" }
    methods:  [POST]

frontend_complete_skill:
    path:     /complete-skill
    defaults: { _controller: "FrontendBundle:User:completeSkill" }
    methods:  [POST]

frontend_get_user:
    path:     /get-user/{id}
    defaults: { _controller: "FrontendBundle:User:getUser" }
    methods:  [GET]

frontend_get_profile_img:
    path:     /get-profile-image/{id}
    defaults: { _controller: "FrontendBundle:User:getProfileImage" }
    methods:  [GET]

frontend_get_user_status:
    path:     /get-user-status/{id}
    defaults: { _controller: "FrontendBundle:User:getUserStatus" }
    methods:  [GET]

frontend_get_user_random:
    path:     /get-user-random
    defaults: { _controller: "FrontendBundle:User:getUsersRandom" }
    methods:  [POST]
    
frontend_get_all_users:
    path:     /get-all-users
    defaults: { _controller: "FrontendBundle:User:getAllUsers" }
    methods:  POST
    
frontend_get_all_users_filter:
    path:     /get-all-users-filter
    defaults: { _controller: "FrontendBundle:User:getAllUsersFilter" }
    methods:  POST

frontend_check_if_player:
    path:     /check-if-player/{id}
    defaults: { _controller: "FrontendBundle:User:checkIfPlayerUser" }
    methods:  [GET]
    
frontend_change_password:
    path:     /change-password
    defaults: { _controller: "FrontendBundle:User:changePassword" }
    methods:  POST


