frontend_notice:
        resource: "@FrontendBundle/Resources/config/routing/notice.yml"
        prefix:   /notice

frontend_map:
        resource: "@FrontendBundle/Resources/config/routing/map.yml"
        prefix:   /map

frontend_login:
        resource: "@FrontendBundle/Resources/config/routing/auth.yml"
        prefix:   /auth

frontend_user:
        resource: "@FrontendBundle/Resources/config/routing/user.yml"
        prefix:   /user

frontend_request_friend:
        resource: "@FrontendBundle/Resources/config/routing/requestfriend.yml"
        prefix:   /requestfriend

frontend_request_match:
        resource: "@FrontendBundle/Resources/config/routing/requestmatch.yml"
        prefix:   /requestmatch

frontend_match:
        resource: "@FrontendBundle/Resources/config/routing/match.yml"
        prefix:   /match

frontend_club_favorite:
        resource: "@FrontendBundle/Resources/config/routing/clubfavorite.yml"
        prefix:   /club-favorite

frontend_tournament:
        resource: "@FrontendBundle/Resources/config/routing/tournament.yml"
        prefix:   /tournament

frontend_notification:
        resource: "@FrontendBundle/Resources/config/routing/notification.yml"
        prefix:   /notification
