frontend_notice:
        resource: "@FrontendBundle/Resources/config/routing/notice.yml"
        prefix:   /notice

frontend_map:
        resource: "@FrontendBundle/Resources/config/routing/map.yml"
        prefix:   /map