backend_home:
  resource: "@BackendBundle/Resources/config/routes/home.yml"
  prefix: /

backend_notice:
  resource: "@BackendBundle/Resources/config/routes/notice.yml"
  prefix: /

backend_user:
  resource: "@BackendBundle/Resources/config/routes/user.yml"
  prefix: /

backend_playerUser:
  resource: "@BackendBundle/Resources/config/routes/playerUser.yml"
  prefix: /

backend_skillUser:
  resource: "@BackendBundle/Resources/config/routes/skillUser.yml"
  prefix: /

backend_requestFriend:
  resource: "@BackendBundle/Resources/config/routes/requestFriend.yml"
  prefix: /

backend_score:
  resource: "@BackendBundle/Resources/config/routes/score.yml"
  prefix: /

backend_match:
  resource: "@BackendBundle/Resources/config/routes/match.yml"
  prefix: /

backend_favoriteClub:
  resource: "@BackendBundle/Resources/config/routes/favoriteClub.yml"
  prefix: /